# Generated by Django 4.1.3 on 2024-05-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_title',
            new_name='title',
        ),
    ]
