# Generated by Django 4.1.3 on 2024-05-10 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_blog_title_blogs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
