# Generated by Django 4.1.3 on 2024-05-10 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogs_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
